version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: mongodb

  server:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
    volumes:
      - ./src:/app/src
      - ./seeds:/app/seeds