query Product($id: ID!) {
  product(id: $id) {
    _id
    name
    description
    originalPrice
    type
    price
    pictures
    hashtags
    colors {
      _id
      color
    }
    sizes {
      _id
      size
    }
    promotionStart
    promotionEnd
    owner {
      _id
      firstName
      middleName
      lastName
      avatar
    }
    createAt

    selectedSize @client
    selectedColor @client
  }
}