query Product($id: ID!) {
  product(id: $id) {
    _id
    name
    description
    originalPrice
    type
    price
    pictures
    colors
    sizes

    selectedSize @client
    selectedColor @client
  }
}