query Messages($id: ID!) {
  me {
    _id
    traderoom(id: $id) {
      _id
      participants {
        _id
        firstName
        avatar
      }
      messages {
        _id
        owner {
          _id
          firstName
          avatar
        }
        content {
          ... on TextContent {
            text
          }
          ... on PictureContent {
            pictureUrl
            size
          }
          ... on CommandContent {
            command
            arguments
          }
        }
        createAt
      }
    }
  }
}