# Root Query
type Query {
  helloworld: String

  me: UserType

  intl(locale: String!): [IntlMessage]
  
  search(keyword: String!, first: Int, after: Int): ProductPage

  product(id: ID!): Product

  categorys: [String]
}