# Root Query
type Query {
  helloworld: String

  me: UserType

  intl(locale: String!): [IntlMessage]
  
  search(keywords: [Keyword], first: Int, after: Int): ProductPage

  product(id: ID!): Product

  user(id: ID!): UserType

  hashtags: [String]
}