query SearchQuery($keywords: [Keyword]) {
  search(keywords: $keywords) {
    totalCount
    edges {
      node {
        _id
        name
        description
        hashtags
        pictures
        owner {
          _id
          firstName
          middleName
          lastName
        }
      }
    }
  }
}