query SearchQuery($keywords: [Keyword], $after: ID, $first: Int) {
  search(keywords: $keywords, after: $after, first: $first) {
    edges {
      node {
        _id
        name
        description
        hashtags
        pictures
        owner {
          _id
          firstName
          middleName
          lastName
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
