type OrderReceipt implements Node {
  _id: ID!

  product: Product!
  creator: UserType!

  size: Size!
  color: Color!
  numberOfItems: Int!

  deliverAddress: Address
  trackingId: String
  remark: String

  paymentMethod: PaymentMethod
  paymentCompletedAt: Date
  paymentCompleted: Boolean

  productDeliveredAt: Date
  productDelivered: Boolean

  productReceivedAt: Date
  productReceived: Boolean

  createAt: Date!
  updateAt: Date!
}