input OrderReceiptOrdering {
  sort: OrderReceiptSort!
  direction: Direction! = ASC
}

enum OrderReceiptSort {
  paymentCompletedAt
  productDelivered
  productReceived
  createAt
  updateAt
  productOwner
  creator
}

type OrderReceiptEdges implements Edges {
  node: OrderReceipt!
  cursor: ID!
}

type OrderReceiptPage implements Page {
  totalCount: Int!
  edges: [OrderReceiptEdges]
  pageInfo: PageInfo
}

enum OrderReceiptStatus {
  CREATED
  PAID
  DELIVERED
  RECEIVED
}

type OrderReceipt implements Node {
  _id: ID!

  product: Product!
  creator: UserType!

  size: Size!
  color: Color!

  trackingId: String
  remark: String

  deliverAddress: Address
  paymentMethod: PaymentMethod

  status: OrderReceiptStatus!
  paymentCompletedAt: Date
  # paymentCompleted: Boolean
  productDeliveredAt: Date
  # productDelivered: Boolean
  productReceivedAt: Date
  # productReceived: Boolean

  createAt: Date!
  updateAt: Date!
}