# Account data type
type Account {
  # Email
  email: String
  # Facebook access code
  facebookAccessCode: String
  # Google access code
  googleAccessCode: String
}

# Address type
type Address implements Node {
  _id: ID!
  # Address detail
  address: String!
  # City
  city: String!
  # Country
  country: String!
  # Zip code
  zip: String!
}

# Payment Method type
type PaymentMethod implements Node {
  _id: ID!
  # Credit card number
  creditCardNumber: String!
}

enum GenderEnum {
  Male
  Female
}

# User interface
interface UserType {
  _id: ID!
  # First name
  firstName: String!
  # Middle name
  middleName: String
  # Last name
  lastName: String!
  # Gender
  gender: GenderEnum!
  # Telephone number
  telNumber: String
  # Account data
  account: Account
  # Addresses
  address(id: ID): Address
  addresses: [Address]
  # Paymethods
  paymentMethod(id: ID): PaymentMethod
  paymentMethods: [PaymentMethod]
  # User avatar
  avatar: String

  # Order receipts
  orderReceipts: [OrderReceipt]

  createAt: Date!
  updateAt: Date!
}

# User type
type User implements UserType, Node {
  _id: ID!
  # First name
  firstName: String!
  # Middle name
  middleName: String
  # Last name
  lastName: String!
  # Gender
  gender: GenderEnum!
  # Telephone number
  telNumber: String
  # Account data
  account: Account
  # Addresses
  address(id: ID): Address
  addresses: [Address]
  # Paymethods
  paymentMethod(id: ID): PaymentMethod
  paymentMethods: [PaymentMethod]
  # User avatar
  avatar: String

  # Order receipts
  orderReceipts: [OrderReceipt]

  createAt: Date!
  updateAt: Date!
}

enum OrderReceiptStatus {
  OPEN,
  DELIVERED,
  CLOSE,
}

# Co-Seller type
type CoSeller implements UserType, Node {
  _id: ID!
  # First name
  firstName: String!
  # Middle name
  middleName: String
  # Last name
  lastName: String!
  # Gender
  gender: GenderEnum!
  # Telephone number
  telNumber: String
  # Account data
  account: Account
  # Addresses
  address(id: ID): Address
  addresses: [Address]
  # Paymethods
  paymentMethod(id: ID): PaymentMethod
  paymentMethods: [PaymentMethod]
  # User avatar
  avatar: String

  # Order receipts
  orderReceipts: [OrderReceipt]
  
  # CoSeller flag
  coseller: Boolean!
  # Products's Own
  products: ProductPage!

  # Buy order receipts with status
  buyOrderReceipts(status: OrderReceiptStatus): [OrderReceipt]
  # Count order receipts with status
  totalBuyOrderReceipts(status: OrderReceiptStatus): Int

  createAt: Date!
  updateAt: Date!
}