# Edges for ProductQuery
type ProductEdges implements Edges {
  node: Product!
  cursor: ID!
}

# Product relay-style pagination query
type ProductPage implements Page {
  totalCount: Int!
  edges: [ProductEdges]
  pageInfo: PageInfo
}

enum ProductEnum {
  Product
  BuyNowProduct
}

# Product
type Product implements Node {
  _id: ID!
  name: String!
  description: String
  
  originalPrice: Int
  type: ProductEnum!
  price: Int

  picture: [String]!
  hashtag: [String]!
  colors: [String]
  sizes: [String]

  promotionStart: Date!
  promotionEnd: Date!
  owner: CoSeller!
  
  createAt: Date!
  updateAt: Date!

  suggestProducts: [Product]
}
